name: Tests
on: [push, pull_request]
jobs:
  tests:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: [3.8, 3.9, "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: setup.py
      - run: pip install -e .[test]
      - name: pytest scrapyd --cov=. --cov-report=xml
      - name: Run integration tests
        run: |
          printf "[scrapyd]\nusername = hello12345\npassword = 67890world\n" > scrapyd.conf
          mkdir logs
          scrapyd > scrapyd.log 2>&1 &
          sleep 1
          pytest integration_tests
          cat scrapyd.log
          kill %%
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/reports/
          env_vars: OS,PYTHON
          fail_ci_if_error: false
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          # https://github.com/codecov/codecov-action/issues/476
          # path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
